apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: ecommerce
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://shaikmohinudin799:Khaja%4095508@shop-project.woqfeg3.mongodb.net/ecommerceDB?retryWrites=true&w=majority"