apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: ecommerce
type: Opaque
stringData:
  MONGO_URI: "mongodb://admin:Admin%4012345@mongodb-client.ecommerce.svc.cluster.local:27017/admin?authSource=admin"