replicaCount: 2

otel: 
  enabled: true

image:
  repository: 077419561607.dkr.ecr.us-east-1.amazonaws.com/backendapp
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

containerPort: 5000

env:
  PORT: "5000"

secret:
  mongoUri: mongodb://admin:Admin%4012345@mongodb-client.ecommerce.svc.cluster.local:27017/admin?authSource=admin
resources: {}